FROM node:22-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

ARG ORULZIP_COMMIT_SHA=unknown
ARG ORULZIP_DEPLOYED_AT_KST=local

ENV HOST=0.0.0.0
ENV ORULZIP_COMMIT_SHA=$ORULZIP_COMMIT_SHA
ENV ORULZIP_DEPLOYED_AT_KST=$ORULZIP_DEPLOYED_AT_KST

CMD ["npm", "run", "dev"]
